#!/bin/sh

if [ "$1" = "unix" ]; then
    DUH_COMPILER=Unix
    DUH_MAKEFILE=makefile.uni
else
    cat << EOF
Usage: fix unix

EOF
    exit
fi

echo "Configuring DUMBOGG for $DUH_COMPILER..."

cat << EOF > makefile
# generated by fix.sh
include make/$DUH_MAKEFILE
EOF

echo "Done! Now run makeall.sh or makelib.sh to start the compilation."

